package V.E.A.F.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Action_Constraints extends BaseConstraintsDescriptor {
  public Action_Constraints() {
    super(CONCEPTS.Action$tj);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Action$tj = MetaAdapterFactory.getConcept(0xf152af7d92d2462fL, 0xacb4a6902db66b9dL, 0x1900d2d6a86e7681L, "V.E.A.F.structure.Action");
  }
}
