package V.E.A.F.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class VEAF_Constraints extends BaseConstraintsDescriptor {
  public VEAF_Constraints() {
    super(CONCEPTS.VEAF$mX);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept VEAF$mX = MetaAdapterFactory.getConcept(0xf152af7d92d2462fL, 0xacb4a6902db66b9dL, 0x27d147c85ff679c8L, "V.E.A.F.structure.VEAF");
  }
}
