package V.E.A.F.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_UNARY_OPERATOR extends EnumerationDescriptorBase {

  public EnumerationDescriptor_UNARY_OPERATOR() {
    super(0xf152af7d92d2462fL, 0xacb4a6902db66b9dL, 0x7ae59a00bc6250c6L, "UNARY_OPERATOR", "r:79efd526-4965-4b82-846b-97823ace55e0(V.E.A.F.structure)/8855653570245185734");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NOT_0 = new EnumerationDescriptor.MemberDescriptor("NOT", "NOT", 0x7ae59a00bc6250c8L, "r:79efd526-4965-4b82-846b-97823ace55e0(V.E.A.F.structure)/8855653570245185736");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf152af7d92d2462fL, 0xacb4a6902db66b9dL, 0x7ae59a00bc6250c6L, 0x7ae59a00bc6250c8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NOT_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NOT":
        return myMember_NOT_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
