package V.E.A.F.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OPERATOR extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OPERATOR() {
    super(0xf152af7d92d2462fL, 0xacb4a6902db66b9dL, 0x31e1baf5f2d0a5b6L, "OPERATOR", "r:79efd526-4965-4b82-846b-97823ace55e0(V.E.A.F.structure)/3594359543121880502");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_AND_0 = new EnumerationDescriptor.MemberDescriptor("AND", "AND", 0x31e1baf5f2d0a5b7L, "r:79efd526-4965-4b82-846b-97823ace55e0(V.E.A.F.structure)/3594359543121880503");
  private final EnumerationDescriptor.MemberDescriptor myMember_OR_0 = new EnumerationDescriptor.MemberDescriptor("OR", "OR", 0x31e1baf5f2d0a6c5L, "r:79efd526-4965-4b82-846b-97823ace55e0(V.E.A.F.structure)/3594359543121880773");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf152af7d92d2462fL, 0xacb4a6902db66b9dL, 0x31e1baf5f2d0a5b6L, 0x31e1baf5f2d0a5b7L, 0x31e1baf5f2d0a6c5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_AND_0, myMember_OR_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "AND":
        return myMember_AND_0;
      case "OR":
        return myMember_OR_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
